-- Phase 2 Restaurants
create extension if not exists pgcrypto;
create table if not exists public.restaurants(id uuid primary key default gen_random_uuid(),name text not null,address text,phone text,email text,color text default '#111827',logo_url text,opening_hours jsonb not null default '{}'::jsonb,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.restaurants add column if not exists address text; alter table public.restaurants add column if not exists phone text; alter table public.restaurants add column if not exists email text; alter table public.restaurants add column if not exists color text default '#111827'; alter table public.restaurants add column if not exists logo_url text; alter table public.restaurants add column if not exists opening_hours jsonb not null default '{}'::jsonb; alter table public.restaurants add column if not exists active boolean not null default true; alter table public.restaurants add column if not exists updated_at timestamptz not null default now();
create table if not exists public.user_restaurants(user_id uuid not null references auth.users(id) on delete cascade,restaurant_id uuid not null references public.restaurants(id) on delete cascade,primary key(user_id,restaurant_id));
alter table public.restaurants enable row level security; alter table public.user_restaurants enable row level security;
drop policy if exists restaurants_select_authenticated on public.restaurants; drop policy if exists restaurants_write_admin on public.restaurants; drop policy if exists user_restaurants_select_authenticated on public.user_restaurants;
create policy restaurants_select_authenticated on public.restaurants for select to authenticated using(true);
create policy restaurants_write_admin on public.restaurants for all to authenticated using(exists(select 1 from public.profiles where profiles.id=auth.uid() and profiles.is_active=true and profiles.role in('super_admin','admin'))) with check(exists(select 1 from public.profiles where profiles.id=auth.uid() and profiles.is_active=true and profiles.role in('super_admin','admin')));
create policy user_restaurants_select_authenticated on public.user_restaurants for select to authenticated using(user_id=auth.uid() or exists(select 1 from public.profiles where profiles.id=auth.uid() and profiles.role in('super_admin','admin') and profiles.is_active=true));
insert into public.restaurants(name,active,opening_hours) select 'Jackies Kitchen',true,'{"mon":"10:00-22:00","tue":"10:00-22:00","wed":"10:00-22:00","thu":"10:00-22:00","fri":"10:00-02:00","sat":"10:00-02:00","sun":"10:00-22:00"}'::jsonb where not exists(select 1 from public.restaurants where name='Jackies Kitchen');
